### ISSUE TITLE
Where can I find your paper?

### ISSUE THREAD

**Issue by yuemengyuan** [SeuTao/CVPR19-Face-Anti-spoofing-Attack-Detection-Challenge#10]
Hello, can you post a link to the paper, thank you~

**Comment by tloki** [comment]
http://openaccess.thecvf.com/content_CVPRW_2019/papers/CFS/Shen_FaceBagNet_Bag-Of-Local-Features_Model_for_Multi-Modal_Face_Anti-Spoofing_CVPRW_2019_paper.pdf

**Comment by yuemengyuan** [comment]
@tloki thank you very much~
