### ISSUE TITLE
模式擦除的代码实现和论文有出入

### ISSUE THREAD

**Issue by LuckyDoggy** [SeuTao/CVPR19-Face-Anti-spoofing-Attack-Detection-Challenge#13]
您好，您在论文中提到的模式擦除是随机选取一个模式的特征置0，但是代码中的实现时让其变为随机噪声，这里是我理解的问题还是代码实现和论文写确实有出入呢？

**Comment by hhyhcr449** [comment]
我的发现是：
数据随机置0的操作是在在data_fusion.py文件中实现，也就是从数据集中取出的时候就置0了；但是经过network的forward操作之后，原本被置0的数据不为0了，和论文的图有出入

**Comment by ayantian** [comment]
您好，请问可以要一下论文的名字么？readme里面没有找到论文的链接。

**Comment by liguiyuan** [comment]
您好，能提供一下论文地址吗，我找不到。

**Comment by 350611906a** [comment]
困扰解开，多谢解读。
