### ISSUE TITLE
代码中缺少文件 data_helper

### ISSUE THREAD

**Issue by HulkMaker** [SeuTao/CVPR19-Face-Anti-spoofing-Attack-Detection-Challenge#14]
执行train命令的时候，会出错：
ModuleNotFoundError: No module named 'data_helper'

**Comment by hhyhcr449** [comment]
加一个.就行了:
from .data_helper import *

**Comment by Homura2333** [comment]
你好，加了之后报错No such file or directory: '/data1/shentao/DATA/CVPR19_FaceAntiSpoofing/train_list.txt' 请问您知道是什么原因吗
