### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/data1/shentao/DATA/CVPR19_FaceAntiSpoofing/train_list.txt'

### ISSUE THREAD

**Issue by marcoippolito** [SeuTao/CVPR19-Face-Anti-spoofing-Attack-Detection-Challenge#16]
(CVPR19) (base) marco@pc:~/antiFaceSpoofing/CVPR19-Face-Anti-spoofing-master$  
      CUDA_VISIBLE_DEVICES=0 python3 train_Fusion_CyclicLR.py --model=model_A 
      --image_size=48
    Namespace(batch_size=128, cycle_inter=50, cycle_num=10, image_mode='fusion',  
    image_size=48, mode='train', model='model_A', pretrained_model=None, train_fold_index=-1)
	    out_dir      = ./models/model_A_fusion_48

	    <additional comments>
	      ... xxx baseline  ... 

    ** dataset setting **
    fold: -1
    fusion
    train
    fold index set:  -1
    Traceback (most recent call last):
      File "train_Fusion_CyclicLR.py", line 254, in <module>
        main(config)
      File "train_Fusion_CyclicLR.py", line 231, in main
        run_train(config)
      File "train_Fusion_CyclicLR.py", line 48, in run_train
        fold_index=config.train_fold_index)
      File "/home/marco/antiFaceSpoofing/CVPR19-Face-Anti-spoofing-master/process
    /data_fusion.py", line 22, in __init__
        self.set_mode(self.mode,self.fold_index)
      File "/home/marco/antiFaceSpoofing/CVPR19-Face-Anti-spoofing-master/process
    /data_fusion.py", line 41, in set_mode
        self.train_list = load_train_list()
      File "/home/marco/antiFaceSpoofing/CVPR19-Face-Anti-spoofing-master/process
    /data_helper.py", line 13, in load_train_list
        f = open(DATA_ROOT + '/train_list.txt')
    FileNotFoundError: [Errno 2] No such file or directory: '/data1/shentao
      /DATA/CVPR19_FaceAntiSpoofing/train_list.txt'

**Comment by zhangxiaopang88** [comment]
Hello, have you solved your problem? I have the same problem, but it hasn't been solved yet.

**Comment by phamthienvuong98** [comment]
hi, have you solved it ?????

**Comment by Homura2333** [comment]
> hi, have you solved it ?????

Hello , I have the same problem. Have you solved it now?
