### ISSUE TITLE
单模式红外人脸测试不准？

### ISSUE THREAD

**Issue by zhangxiaopang88** [SeuTao/CVPR19-Face-Anti-spoofing-Attack-Detection-Challenge#18]
您好，非常感谢你的项目给我很大的帮助，但是我用红外摄像机，红外图片检测出人脸后送入网络测试，不管是活体图片还是照片测试结果接近1，不知道是我的测试代码有问题，还是我的测试方法有问题。您能给出一些建议吗

**Comment by zhangxiaopang88** [comment]
@SeuTao

**Comment by SeuTao** [comment]
比赛数据采集是用的realsense的摄像头，且做过一定的预处理，我理解跟你使用的真实场景数据差异应该很大，直接测试效果估计不理想。

**Comment by zhangxiaopang88** [comment]
您好，还想问一个问题，您提供的model_A_ir_32文件夹内的模型是只使用近红外数据训练的模型吗？

**Comment by zhangxiaopang88** [comment]
@SeuTao

**Comment by SeuTao** [comment]
是的

**Comment by riskeverything** [comment]
应该是数据源的问题，比赛数据源感觉就很怪，和自己使用的ir图像拍出来差异巨大。想问下，你后来有自己采集数据集嘛？有的话，可否分享下呢？我用一些其他模型，单IR差不多可以做到90%了。不过没有其它数据来做测试了。

**Comment by lawo123** [comment]
你好，我看原论文中单IR 48*48的结果TPR@FPR 10E-4=98.6，但是我加载您的预训练模型测试的结果为ACER : 0.0110,TPR@FPR=10E-2 :0.9872,TPR@FPR=10E-2 :0.9872,TPR@FPR=10E-3 :0.8242,TPR@FPR=10E-4 :0.5246
![image](https://user-images.githubusercontent.com/44777088/99774725-28ad8700-2b49-11eb-8024-ccf92cb615e7.png)
@SeuTao

**Comment by weilanShi** [comment]
> 应该是数据源的问题，比赛数据源感觉就很怪，和自己使用的ir图像拍出来差异巨大。想问下，你后来有自己采集数据集嘛？有的话，可否分享下呢？我用一些其他模型，单IR差不多可以做到90%了。不过没有其它数据来做测试了。

你好，你后来用哪个模型在单IR上效果比较好啊，可以分享下吗
