### ISSUE TITLE
Different mean of models (baseline, A, B, C)?

### ISSUE THREAD

**Issue by VuHoangvn** [SeuTao/CVPR19-Face-Anti-spoofing-Attack-Detection-Challenge#20]
Can you tell me the meaning of models that you experiment in this repo?
I can't find it on your paper.

**Comment by hoangtd12654** [comment]
how to run project , 
after running the command line: CUDA_VISIBLE_DEVICES = 0 python train_CyclicLR.py --model = model_A --image_mode = color --image_size = 48. I have a problem with:
Traceback (most interesting call last):
  File "train_CyclicLR.py", line 6, in <module>
    from process.data import *
  File "/home/linux/Documents/asd/CVPR19-Face-Anti-spoofing/process/data.py", line 3, in <module>
    from data_helper import *
ModuleNotFoundError: No module named 'data_helper'

**Comment by VuHoangvn** [comment]
just add dot before it: 
`from .data_helper import * `

**Comment by hoangtdTcom** [comment]
> just add dot before it:
> `from .data_helper import * `

bạn ơi, mình bỏ dữ liệu ở đâu để nó có thể chạy được vậy

**Comment by hoangtdTcom** [comment]
how to set up an input data structure for successful program execution?

**Comment by VuHoangvn** [comment]
File "**/home/linux/Documents/asd/CVPR19-Face-Anti-spoofing/process/data.py**", line 3, in
from data_helper import *
ModuleNotFoundError: No module named 'data_helper'

**Comment by Doanhdz** [comment]
When i tried to infer model_fusion with model_name='baseline' i met this error
No module named 'model.backbone.senet' model? 
Can you help me solve this?

**Comment by phamthienvuong98** [comment]
hi @VuHoangvn,
Irrelevant, but would you like to tell me how to find this file:
FileNotFoundError: [Errno 2] No such file or directory: '/data1/shentao/DATA/CVPR19_FaceAntiSpoofing/test_public_list.txt'
Thank you so much!
Best regards,
ThienVuong
