### ISSUE TITLE
about model

### ISSUE THREAD

**Issue by XinyingZheng** [SeuTao/CVPR19-Face-Anti-spoofing-Attack-Detection-Challenge#21]
The training input of the model is the whole face, 
and the local patches are not reflected

**Comment by Sally-fyk** [comment]
我也十分疑惑这个问题，请问你有发现什么吗

**Comment by 350611906a** [comment]
It use local patches,but don't use patch_size param,It base on image_size param, then, crop pic  to get the local pic.
