### ISSUE TITLE
单IR测试结果和原论文不符

### ISSUE THREAD

**Issue by lawo123** [SeuTao/CVPR19-Face-Anti-spoofing-Attack-Detection-Challenge#24]
你好，我看原论文中单IR 48*48的结果TPR@FPR 10E-4=98.6，但是我加载您的预训练模型测试的结果为ACER : 0.0110,TPR@FPR=10E-2 :0.9872,TPR@FPR=10E-2 :0.9872,TPR@FPR=10E-3 :0.8242,TPR@FPR=10E-4 :0.5246
![image](https://user-images.githubusercontent.com/44777088/100038763-31e76e00-2e3f-11eb-80af-34e18484b533.png)
@SeuTao @huangyuyu0426

**Comment by Doanhdz** [comment]
Can you find  'model.backbone.senet' ? I try infer fusion model with model_name=''baseline' but i found this error 
No module named 'model.backbone.senet' model

**Comment by lawo123** [comment]
> Can you find 'model.backbone.senet' ? I try infer fusion model with model_name=''baseline' but i found this error
> No module named 'model.backbone.senet' model

you can change `from model.backbone.senet import SEModule` to `from model.backbone.FaceBagNet import SEModule` in model_fusion/model_baseline_SEFusion.py

**Comment by Doanhdz** [comment]
Thanks for your reply i will try 

Được gửi từ iPhone của tôi

Vào ngày 7 thg 12, 2020, lúc 09:03, lawo123 <notifications@github.com> đã viết:
