### ISSUE TITLE
no module named 'augmentation'

### ISSUE THREAD

**Issue by Homura2333** [SeuTao/CVPR19-Face-Anti-spoofing-Attack-Detection-Challenge#25]
train using CUDA_VISIBLE_DEVICES=0 python train_Fusion_CyclicLR.py --model=model_A --image_size=48

**Comment by KiLJ4EdeN** [comment]
> train using CUDA_VISIBLE_DEVICES=0 python train_Fusion_CyclicLR.py --model=model_A --image_size=48

Do the imports like this `from .augmentation import *`, this way the modules are imported from the same directory.
This is probably because you are using an IDE.
You could do the same for similar import errors.
