### ISSUE TITLE
softmax_cross_entropy_criterion

### ISSUE THREAD

**Issue by Paidalin** [SeuTao/CVPR19-Face-Anti-spoofing-Attack-Detection-Challenge#3]
你好， 我在train的代码中发现softmax_cross_entropy_criterion，请问这个是什么？网络上也没有搜索到这个的相关内容。

**Comment by Paidalin** [comment]
submission(out,save_dir+'_noTTA.txt', mode='test')
submission(probs,save_name, mode='test')
同时submission()，也没有找到相关内容

**Comment by Adarine99** [comment]
> 你好， 我在train的代码中发现softmax_cross_entropy_criterion，请问这个是什么？网络上也没有搜索到这个的相关内容。

请问你找到了嘛？我也没找到出处

**Comment by Adarine99** [comment]
> submission(out,save_dir+'_noTTA.txt', mode='test')
> submission(probs,save_name, mode='test')
> 同时submission()，也没有找到相关内容
submission()这个函数定义在data_helper.py里

**Comment by Paidalin** [comment]
> > 你好， 我在train的代码中发现softmax_cross_entropy_criterion，请问这个是什么？网络上也没有搜索到这个的相关内容。
> 
> 请问你找到了嘛？我也没找到出处

在utils.py文件中

**Comment by Adarine99** [comment]
> > > 你好， 我在train的代码中发现softmax_cross_entropy_criterion，请问这个是什么？网络上也没有搜索到这个的相关内容。
> > 
> > 
> > 请问你找到了嘛？我也没找到出处
> 
> 在utils.py文件中

谢谢啦
