### ISSUE TITLE
请问有大佬能跑通吗？需要改代码吗？

### ISSUE THREAD

**Issue by nit-hmz** [SeuTao/CVPR19-Face-Anti-spoofing-Attack-Detection-Challenge#34]
改完一个error又出现一个error，这份代码能正常跑吗？

**Comment by nit-hmz** [comment]
这是我想infer的时候出现的error:
1.TypeError: get_model() got an unexpected keyword argument 'is_first_bn'（我去看了函数定义，根本就没有is_first_bn这个形参，还缺了两个参数“image_size”和"patch_size"）
2.提供的预训练权重文件夹“models”根本就没有FaceBagNet_color_48，所以实例代码的image_size要改为96
3.NameError: name 'infer_test' is not defined
4.submission也是没有定义

**Comment by nit-hmz** [comment]
UnboundLocalError: local variable 'net' referenced before assignment

**Comment by Cassiel829** [comment]
@nit-hmz 你好，请问 NameError: name 'infer_test' is not defined 这个问题解决了吗

**Comment by Aruen24** [comment]
> @nit-hmz 你好，请问 NameError: name 'infer_test' is not defined 这个问题解决了吗

可以跑通呀，是你环境版本原因吧.
