### ISSUE TITLE
请问哪里能看到您的文章

### ISSUE THREAD

**Issue by andrearita** [SeuTao/CVPR19-Face-Anti-spoofing-Attack-Detection-Challenge#5]
如题，如果有发表文章的话，能否更新一下？谢谢

**Comment by SeuTao** [comment]
http://openaccess.thecvf.com/content_CVPRW_2019/papers/CFS/Shen_FaceBagNet_Bag-Of-Local-Features_Model_for_Multi-Modal_Face_Anti-Spoofing_CVPRW_2019_paper.pdf
