### ISSUE TITLE
when will you provide the pre-trained model?

### ISSUE THREAD

**Issue by HulkMaker** [SeuTao/CVPR19-Face-Anti-spoofing-Attack-Detection-Challenge#9]
when will you provide the pre-trained model corresponding to this paper?

**Comment by engmubarak48** [comment]
Yes, is there a plan of providing the pre-trained model

**Comment by tloki** [comment]
When could we expect pre-trained models?

**Comment by zhleternity** [comment]
Expect pre-trained model
